In [32]:
import anndata as ad
sample_list = ["N1","N2", "N3", "N4", "N5", "P1", "P2","P3", "P4", "P5"]
sample = 'P1'
adatas=[]
for sample in sample_list:
    adata_data = F'./sample_data/PRO/{sample}/{sample}_pro.h5ad'
    adata = ad.read_h5ad(adata_data)
    adatas.append(adata)
    
adata_merged = ad.concat(
    adatas,
    axis=0,                 # 0=obs(细胞)方向拼接
    join="outer",           # outer=取基因并集；inner=取交集
    label="batch",          # 在 obs 里新增一列 batch
    #keys=[f"s{i}" for i in range(len(adatas))],  # 每个对象的批次名
    index_unique="-",       # 防止 obs_names 重复：如 cell1 -> s0-cell1
    merge="same",           # uns/var/obsm等冲突时的策略（稳妥）
)

adata_merged.obs['img_path'] = (adata_merged.obs["sample_index"].astype(str)+'/'+adata_merged.obs["sample_index"].astype(str)+'_he_'+adata_merged.obs["patch_i"].astype(str)+'.jpg')

adata_merged.write_h5ad("./sample_data/PRO/adata_all.h5ad")

In [11]:
adatas = [adata, adata2,]
adata_merged = ad.concat(
    adatas,
    axis=0,                 # 0=obs(细胞)方向拼接
    join="outer",           # outer=取基因并集；inner=取交集
    label="batch",          # 在 obs 里新增一列 batch
    #keys=[f"s{i}" for i in range(len(adatas))],  # 每个对象的批次名
    index_unique="-",       # 防止 obs_names 重复：如 cell1 -> s0-cell1
    merge="same",           # uns/var/obsm等冲突时的策略（稳妥）
)

In [13]:
adata_merged.X.shape

(2763, 774600)

In [14]:
print(adata)  
print(adata.shape)

AnnData object with n_obs × n_vars = 1365 × 774600
    obs: 'sample_index', 'patch_i', 'img_path', 'img_h', 'img_w', 'img_c'
    uns: 'arr_shape', 'flatten_order'
(1365, 774600)

In [15]:
adata.obs

,sample_index,patch_i,img_path,img_h,img_w,img_c
0,P1,0,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
1,P1,1,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
2,P1,2,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
3,P1,3,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
4,P1,4,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
...,...,...,...,...,...,...
1360,P1,1360,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
1361,P1,1361,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
1362,P1,1362,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
1363,P1,1363,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
1364,P1,1364,D:\test\Super_resolution\data\HE_target\datase...,122,124,3

In [30]:
adata_merged.obs['img_path'] = (adata_merged.obs["sample_index"].astype(str)+'/'+adata_merged.obs["sample_index"].astype(str)+'_he_'+adata_merged.obs["patch_i"].astype(str)+'.jpg')

In [28]:
adata_merged.obs['img_path'] = adata_merged.obs["sample_index"]

In [31]:
adata_merged.obs

       sample_index  patch_i           img_path  img_h  img_w  img_c batch
0-0              P1        0     P1/P1_he_0.jpg    122    124      3     0
1-0              P1        1     P1/P1_he_1.jpg    122    124      3     0
2-0              P1        2     P1/P1_he_2.jpg    122    124      3     0
3-0              P1        3     P1/P1_he_3.jpg    122    124      3     0
4-0              P1        4     P1/P1_he_4.jpg    122    124      3     0
...             ...      ...                ...    ...    ...    ...   ...
1393-1           P2     1393  P2/P2_he_1393.jpg    133    132      3     1
1394-1           P2     1394  P2/P2_he_1394.jpg    133    132      3     1
1395-1           P2     1395  P2/P2_he_1395.jpg    133    132      3     1
1396-1           P2     1396  P2/P2_he_1396.jpg    133    132      3     1
1397-1           P2     1397  P2/P2_he_1397.jpg    133    132      3     1

[2763 rows x 7 columns]

In [9]:
adata.obsm.keys()

KeysView(AxisArrays with keys: )

In [6]:
pro.obs.head()

,sample_index,patch_i,img_path,img_h,img_w,img_c
0,P1,0,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
1,P1,1,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
2,P1,2,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
3,P1,3,D:\test\Super_resolution\data\HE_target\datase...,122,124,3
4,P1,4,D:\test\Super_resolution\data\HE_target\datase...,122,124,3